#!/usr/bin/env bash

# Colors taken from tokyonight theme
cyan="0xff00ffff"
blue="0xff7aa2f7"

options=(
  active_color="$cyan"
  inactive_color="$blue"
  hidpi=on
  style=round
  width=6.0
  blacklist="Screen Studio"
)

borders "${options[@]}"